run:
  timeout: 4m

linters:
  disable-all: false
  enable:
    - gocyclo
    - misspell
    - nilerr
    - unparam
    - gosec
    - unused
    - govet
    - gosimple
    - errorlint
    - errcheck
    - dupl
    - dogsled
    - cyclop
    - exhaustive
    - funlen
    - gocognit
    - nestif
    - goconst
    - gocritic
    - gofmt
    - revive
    - lll
    - makezero
    - nakedret
    - prealloc
    - nolintlint
    - staticcheck
    - thelper
    - whitespace
  disable:
    - godot


linters-settings:
  gocyclo:
    min-complexity: 20

  misspell:
    locale: US

  unused:
    go: "1.16"

  unparam:
    check-exported: true

  govet:
    check-shadowing: false

  gosimple:
    go: "1.16"
    checks: [ "all" ]

  errorlint:
    errorf: true
    asserts: true
    comparison: true

  errcheck:
    check-type-assertions: true
    check-blank: true

  dupl:
    threshold: 100

  dogsled:
    max-blank-identifiers: 2

  cyclop:
    max-complexity: 15
    package-average: 0.0
    skip-tests: true

  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false

  funlen:
    lines: 80
    statements: 50

  gocognit:
    min-complexity: 15

  nestif:
    min-complexity: 5

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-checks:
      - ruleguard
    enabled-tags:
      - performance
    disabled-tags:
      - experimental
    settings:
      captLocal:
        paramsOnly: true
      elseif:
        skipBalanced: true
      hugeParam:
        sizeThreshold: 80
      rangeExprCopy:
        sizeThreshold: 512
        skipTestFuncs: true
      rangeValCopy:
        sizeThreshold: 32
        skipTestFuncs: true
      ruleguard:
        rules: ''
      underef:
        skipRecvDeref: true

  godot:
    scope: declarations
    capital: false

  gofmt:
    simplify: true

  revive:
    ignore-generated-header: true
    severity: warning

  lll:
    line-length: 160
    tab-width: 1

  makezero:
    always: false

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  nolintlint:
    allow-unused: false
    allow-leading-space: true
    allow-no-explanation: []
    require-explanation: true
    require-specific: true

  staticcheck:
    go: "1.16"
    checks: [ "all" ]

  thelper:
    test:
      first: true
      name: true
      begin: true
    benchmark:
      first: true
      name: true
      begin: true
    tb:
      first: true
      name: true
      begin: true

  whitespace:
    multi-if: false
    multi-func: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - funlen
        - gocognit
        - unparam
        - lll
        - goconst