apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mqtt-pinger.fullname" . }}
  labels:
    {{- include "mqtt-pinger.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mqtt-pinger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "mqtt-pinger.selectorLabels" . | nindent 8 }}
      {{- with .Values.extraPodLabels }}
        {{ toYaml . | indent 8 | trim }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - --broker-address
            {{- range .Values.configuration.brokers }}
            - {{ . | quote }}
            {{- end }}
            - --metrics-port
            - {{ .Values.configuration.metricsPort | quote }}
            - --ping-interval
            - {{ .Values.configuration.pingInterval | quote }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.configuration.metricsPort }}
              name: metrics
              protocol: TCP
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
