name: End-to-End

on:
  pull_request:
    branches: [ main ]

env:
  NAME: "mqtt-pinger"

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2.3.4
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - name: Prepare
        id: prep
        run: |
          make e2e
